services:
  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env # .gitignored for secrets like JWT_SECRET_KEY
    environment:
      NO_LOCAL_CONFIG_FILES: 1
      PORT: 8080
      RUST_LOG: info,axum_login=warn,tower_sessions=warn

      DB_BACKEND: postgres

      # note that these are redundantly defined below for db as well
      POSTGRES_USER: dreamscroll_pg_user
      #POSTGRES_PASSWORD: NOT HERE SHOULD COME FROM .env file
      POSTGRES_HOST_PORT: db:5432 # note 'db' within Docker network, not localhost
      POSTGRES_DB: dreamscroll_dev1

      STORAGE_BACKEND: gcloud
      STORAGE_GCLOUD_EMULATOR_ENDPOINT: http://fake-gcs:4443
      STORAGE_GCLOUD_BUCKET_NAME: "dreamscroll-dev-media1"

      # Pub/Sub emulator should be invoked manually external of Docker, via
      # `gcloud beta emulators pubsub start --host-port=localhost:8085`
      PUBSUB_EMULATOR_URL_BASE: http://host.docker.internal:8085
      PUBSUB_PROJECT_ID: dreamscroll-local

      #PUBSUB_PUSH_OIDC_AUDIENCE: not used in localdev but required for Cloud Run

      PUBSUB_ILLUMINATION_TOPIC_ID: dreamscroll-illumination

    volumes:
      # Cute way to import/export data from the docker environment
      - ${EXPORT_DIR:-~/Documents/dreamscroll_export}:/app/export

    depends_on:
      db:
        condition: service_healthy
      fake-gcs:
        condition: service_started

  db:
    image: postgres:18
    restart: always
    shm_size: 128mb
    env_file:
      - .env # POSTGRES_PASSWORD comes from secrets here
    environment:
      # Defined redundantly here (should be same as `app` above) so that the 
      # Postgres image can use them to initialize itself upon first run
      POSTGRES_USER: dreamscroll_pg_user
      #POSTGRES_PASSWORD: NOT HERE SHOULD COME FROM .env file
      POSTGRES_DB: dreamscroll_dev1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "dreamscroll_pg_user", "-d", "dreamscroll_dev1", "-q" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Fake-GCS server for local emulation of Google Cloud Storage. 
  #
  # NOTE, if you get "Not Found" errors when attempting to upload to emulator
  # You probably need to create the bucket manually, since the emulator
  # apparently does not (always?) automatically create the bucket for you.
  # After `docker compose up fake-gcs`, can run:
  #
  # curl -X POST -H "Content-Type: application/json" \
  #   http://localhost:4443/storage/v1/b \
  #   -d '{"name": "dreamscroll-dev-media1"}'
  #
  # You can list current buckets with:
  # curl http://localhost:4443/storage/v1/b

  fake-gcs:
    image: fsouza/fake-gcs-server:latest
    restart: unless-stopped
    ports:
      - "4443:4443"
    volumes:
      - gcloud_storage_data:/data
    command: -scheme http -data /data
    # This was super flaky, just forget it
    # healthcheck:
    #   test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4443//_internal/healthcheck" ]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s

volumes:
  postgres_data:
  gcloud_storage_data:


