use super::*;

/// Generate a task id for a submitted task.
///
/// **PLACEHOLDER — DO NOT TRUST THIS.**
///
/// This is a shitty stopgap: it just concatenates the user id, the task type,
/// and a random UUID into a string. It is *not* a real task-identity scheme.
///
/// We need to rethink task identity entirely. Open questions:
/// - Should the id be derived from the payload (e.g. capture_id) so reruns of
///   the same work are idempotent / dedupe-able? Or should every submission be
///   a fresh, unique id?
/// - Should the id be generated by the queue (which owns the task) rather than
///   by the caller? The queue is the arbiter of task identity.
/// - Should it be a structured type (e.g. a `TaskId` value struct) rather than
///   a raw `String`?
/// - How does it interact with `run_id` for reruns?
///
/// Revisit this before relying on task ids for anything correctness-critical.
pub fn make_task_id<T: Task>(user_id: i32, _task: &T) -> String {
    format!("u{}-{}-{}", user_id, T::task_type(), uuid::Uuid::new_v4())
}
