#printf '{"capture_id":123}' | base64 | tr -d '\n'

POST http://localhost:8080/_wh/cloudtask/illuminate HTTP/1.1
Content-Type: application/json

 {
    "capture_id": 123
}
###

POST http://localhost:8080/_wh/cloudtask/spark HTTP/1.1
Content-Type: application/json

{
    "capture_ids": [537]
}
###