# @name token
# @prompt username
# @prompt password
POST http://localhost:8080/api/token HTTP/1.1
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}
###

GET http://localhost:8080/api/dummy
Authorization: Bearer {{token.response.body.access_token}}

###

GET http://localhost:8080/api/timeline
Authorization: Bearer {{token.response.body.access_token}}

###

GET http://localhost:8080/api/captures?id=1
Authorization: Bearer {{token.response.body.access_token}}

###

GET http://localhost:8080/api/captures
Authorization: Bearer {{token.response.body.access_token}}

###
POST http://localhost:8080/api/captures/import
Authorization: Bearer {{token.response.body.access_token}}
Content-Type: multipart/form-data; boundary=----dreamscrollboundary

------dreamscrollboundary
Content-Disposition: form-data; name="created_at"

2024-01-02T03:04:05Z
------dreamscrollboundary
Content-Disposition: form-data; name="image"; filename="capture.jpg"
Content-Type: image/jpeg

< ./sample.jpg
------dreamscrollboundary--

###
# Returns 204 No Content on success
DELETE http://localhost:8080/api/captures/529
Authorization: Bearer {{token.response.body.access_token}}

###
# Returns 204 No Content on success
POST http://localhost:8080/api/captures/586/archive
Authorization: Bearer {{token.response.body.access_token}}

###
# Returns 204 No Content on success
POST http://localhost:8080/api/captures/572/unarchive
Authorization: Bearer {{token.response.body.access_token}}

###
# Requires an admin JWT token
POST http://localhost:8080/api/admin/users
Authorization: Bearer {{token.response.body.access_token}}
Content-Type: application/json

{
    "username": "mike2",
    "password": "asdfasdfasdf",
    "email": "mike2@dreamscroll.ai"
}